import json
import re
from pathlib import Path

import numpy as np
import pandas as pd


def pick_column(columns, candidates):
    lowered = {c.lower(): c for c in columns}
    for candidate in candidates:
        found = lowered.get(candidate.lower())
        if found:
            return found
    return None


def parse_tier(value):
    if pd.isna(value):
        return 3
    if isinstance(value, (int, np.integer, float, np.floating)):
        return int(value)
    match = re.search(r"(\d+)", str(value))
    return int(match.group(1)) if match else 3


def safe_radar(row, key):
    value = row.get(key, 50)
    if pd.isna(value):
        return 50
    try:
        return int(value)
    except (TypeError, ValueError):
        return 50


source_candidates = [
    Path("output/predictions.csv"),
    Path("relatorio_produto_cassandra.csv"),
]
source_path = next((p for p in source_candidates if p.exists()), None)
if not source_path:
    raise FileNotFoundError("No predictions dataframe found in output/predictions.csv or relatorio_produto_cassandra.csv")

raw_df = pd.read_csv(source_path)

municipio_col = pick_column(raw_df.columns, ["municipio", "Município"])
tier_col = pick_column(raw_df.columns, ["tier", "CASSANDRA_Risk_Tier"])
risk_col = pick_column(raw_df.columns, ["risk_score", "CASSANDRA_Risk_Score"])
var_pop_col = pick_column(raw_df.columns, ["var_pop_pct", "Var_Pop", "var_pop"])
year_col = pick_column(raw_df.columns, ["ano", "Ano", "year", "Year"])

required = {
    "municipio": municipio_col,
    "tier": tier_col,
    "risk_score": risk_col,
    "var_pop_pct": var_pop_col,
}
missing = [name for name, col in required.items() if not col]
if missing:
    raise ValueError(f"Missing required columns in {source_path}: {missing}")

df = pd.DataFrame()
df["municipio"] = raw_df[municipio_col].astype(str).str.strip()
df["tier"] = raw_df[tier_col].apply(parse_tier).astype(int)
df["risk_score"] = pd.to_numeric(raw_df[risk_col], errors="coerce").fillna(0.0)
df["var_pop_pct"] = pd.to_numeric(raw_df[var_pop_col], errors="coerce").fillna(0.0)
if year_col:
    df["ano"] = pd.to_numeric(raw_df[year_col], errors="coerce").fillna(2026).astype(int)
else:
    df["ano"] = 2026

# Preserve optional radar fields when available
for radar_col in [
    "radar_migracao",
    "radar_envelhecimento",
    "radar_economia",
    "radar_habitacao",
    "radar_isolamento",
]:
    if radar_col in raw_df.columns:
        df[radar_col] = raw_df[radar_col]

# ── MAP TIERS ──────────────────────────────────────────────
tier_map = dict(zip(df["municipio"], df["tier"].astype(int)))

# ── GLOBAL STATS ───────────────────────────────────────────
total = len(df)
tier_counts = df["tier"].value_counts().to_dict()
tier4_pct = round(tier_counts.get(4, 0) / total * 100, 1) if total else 0.0
tier3_pct = round(tier_counts.get(3, 0) / total * 100, 1) if total else 0.0
tier2_pct = round(tier_counts.get(2, 0) / total * 100, 1) if total else 0.0
tier1_pct = round(tier_counts.get(1, 0) / total * 100, 1) if total else 0.0

global_stats = {
    "total_municipios": int(total),
    "tier4_count": int(tier_counts.get(4, 0)),
    "tier3_count": int(tier_counts.get(3, 0)),
    "tier2_count": int(tier_counts.get(2, 0)),
    "tier1_count": int(tier_counts.get(1, 0)),
    "tier4_pct": tier4_pct,
    "tier3_pct": tier3_pct,
    "tier2_pct": tier2_pct,
    "tier1_pct": tier1_pct,
    "critical_alert": tier4_pct > 40,
}

# ── NODE DATA (all 308 municipalities) ────────────────────
node_data = {}
for i, (_, row) in enumerate(
    df.sort_values('municipio', ascending=True).iterrows(), 1):
    key = str(i).zfill(3)
    node_data[key] = {
        'heading': row['municipio'].upper(),
        'node':    f'NODE {i:03d}',
        'var_pop': f"{row['var_pop_pct']:+.1f}%",
        'status':  '404' if int(row['tier']) >= 3 else '200',
        'score':   round(float(row['risk_score']), 1),
        'tier':    int(row['tier']),
        'radar':   [50, 50, 50, 50, 50]
    }

# ── ORACLE LOG (all predictions sorted by municipality) ────
oracle_log = []
for i, (_, row) in enumerate(
    df.sort_values("municipio", ascending=True).iterrows(), 1
):
    oracle_log.append(
        {
            "id": str(i).zfill(3),
            "municipio": row["municipio"],
            "tier": int(row["tier"]),
            "score": round(float(row["risk_score"]), 1),
            "var_pop": f"{row['var_pop_pct']:+.1f}%",
            "date": "2026-01-01",
        }
    )

# oracle_log now contains all 308 entries

# ── ASSEMBLE AND EXPORT ────────────────────────────────────
dashboard_data = {
    "tier_map": tier_map,
    "global_stats": global_stats,
    "node_data": node_data,
    "oracle_log": oracle_log,
}

js_output = (
    "// AUTO-GENERATED BY export_dashboard_data.py - DO NOT EDIT\n"
    "var DASHBOARD_DATA = "
    + json.dumps(dashboard_data, ensure_ascii=False, indent=2)
    + ";\n"
    "var TIER_DATA = DASHBOARD_DATA.tier_map;\n"
)

out_path = Path("assets/dashboard_data.js")
out_path.parent.mkdir(parents=True, exist_ok=True)
with out_path.open("w", encoding="utf-8") as f:
    f.write(js_output)

print(f"✓ Source: {source_path}")
print(f"✓ Exported {total} municipalities")
print(f"✓ Tier distribution: {tier_counts}")
print(f"✓ Saved to {out_path}")
